import Hello from "@/app/components/Hello";

export const metadata = {
  title: "Home | Next.js",
  description: "Generated by create next app",
};

export default function Home() {
  console.log("What am I doing here? -- SERVER?");
  return (
    <>
      <h1 className="text-3xl">Welcome to Next.js</h1>
      <Hello />
    </>
  );
}
